In [ ]:
import pandas as pd

# load the csv
df_raw = pd.read_csv("../data/telco_customer_churn.csv")
df = df_raw.copy()
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
# dropping columns
df = df.drop("customerID", axis=1)

In [3]:
# one hot encoding columns
df = pd.get_dummies(df, columns=["InternetService", "PaymentMethod", "Contract"], drop_first=True) 
# baseline is DSL
# baseline is bank transfer(automatic)
# baseline is month-to-month

# converting special columns
df["MultipleLines"] = df["MultipleLines"].replace("No phone service", "No")
df["OnlineSecurity"] = df["OnlineSecurity"].replace("No internet service", "No")
df["OnlineBackup"] = df["OnlineBackup"].replace("No internet service", "No")
df["DeviceProtection"] = df["DeviceProtection"].replace("No internet service", "No")
df["TechSupport"] = df["TechSupport"].replace("No internet service", "No")
df["StreamingTV"] = df["StreamingTV"].replace("No internet service", "No")
df["StreamingMovies"] = df["StreamingMovies"].replace("No internet service", "No")

# converting binary columns
df["gender"] = df["gender"].map({"Male": 1, "Female": 0})

binary_cols = ["Partner", "Dependents", "PhoneService", "MultipleLines", "OnlineSecurity", "OnlineBackup", 
"DeviceProtection", "Churn", "InternetService_Fiber optic", "InternetService_No", 
"PaymentMethod_Credit card (automatic)", "PaymentMethod_Electronic check", "PaymentMethod_Mailed check", 
"Contract_One year", "Contract_Two year", "TechSupport", "StreamingTV", "StreamingMovies", "PaperlessBilling"]

for col in binary_cols:
    df[col] = df[col].map({"Yes": 1, "No": 0, True: 1, False: 0})

In [4]:
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"], errors="coerce"
)

# dropping rows with missing values
df = df.dropna()

In [ ]:
# export clean dataframe to csv

clean_telco_df = df
clean_telco_df.to_csv("../data/clean_telco_df.csv", index=False)

clean_telco_df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,MonthlyCharges,TotalCharges,Churn,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_One year,Contract_Two year
0,0,0,1,0,1,0,0,0,1,0,...,29.85,29.85,0,0,0,0,1,0,0,0
1,1,0,0,0,34,1,0,1,0,1,...,56.95,1889.50,0,0,0,0,0,1,1,0
2,1,0,0,0,2,1,0,1,1,0,...,53.85,108.15,1,0,0,0,0,1,0,0
3,1,0,0,0,45,0,0,1,0,1,...,42.30,1840.75,0,0,0,0,0,0,1,0
4,0,0,0,0,2,1,0,0,0,0,...,70.70,151.65,1,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,1,0,1,...,84.80,1990.50,0,0,0,0,0,1,1,0
7039,0,0,1,1,72,1,1,0,1,1,...,103.20,7362.90,0,1,0,1,0,0,1,0
7040,0,0,1,1,11,0,0,1,0,0,...,29.60,346.45,0,0,0,0,1,0,0,0
7041,1,1,1,0,4,1,1,0,0,0,...,74.40,306.60,1,1,0,0,0,1,0,0
7042,1,0,0,0,66,1,0,1,0,1,...,105.65,6844.50,0,1,0,0,0,0,0,1